#服务器地址
#server: 120.79.182.242:9188
server: 127.0.0.1:9188

#登录令牌
token: ac16alad5a1dk3afysgeaA

#重连间隔时间
sleep: 5

#服务列表
serves:
    -
        addr: 192.168.2.100:80
        type: http
        domain: http.nsp.bincs.cn
    -
        addr: 192.168.2.100:443
        type: https
        domain: https.nsp.bincs.cn
    -
        addr: 192.168.2.100:22
        type: tcp
        port: 999